[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
remappings = ['ds-test/=lib/ds-test/src/']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
