[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 1
wrap_comments = true
gas_reports = ["TLAuctionHouse", "TLStacks721", "TLStacks1155"]
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
