on: [push]

name: Test

jobs:
  check:
    name: Transient Labs Stacks Protocol (sales mechanics)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Instal modules
        run: make install

      - name: Run unit tests
        run: make tests